;	Israel Celis Campagnoli
;	twitter @israelcelis1310
;	https://ve.linkedin.com/in/israelceliscampagnoli
;	Practicas en Assembler Digitales III
;	Universidad Nacional Experimental "Antonio Jóse de Sucre"
;	Vicerectorado "Luis Caballero Mejías"
	
		.model small
		.stack 100h
		.data
LIN1	DB 0FH DUP (20H)
		DB "1.REQUISITOS DE ENTRADA",0AH,0AH,0DH
		DB 0FH DUP (20H)
		DB "2.MATERIAL REQUERIDO",0AH,0AH,0DH
		DB 0FH DUP (20H)
		DB "3.HORARIO",0AH,0AH,0DH
		DB 0FH DUP (20H)
		DB "4.SALIR","$"
LIN2	DB "CEDULA","$"
LIN3	DB "NOMBRE","$"
PAG		DB 00H
BUFFC 	DB 09H DUP (20H)
BUFFN	DB 41 DUP (20H)
CANT  	DB 09H
PERSONAS DB 480 DUP(?)

		.code
		MOV AX,SEG LIN1
		MOV DS,AX
		MOV AX,0500H
		INT 10H
		MOV DX,0000H
		CALL CURSOR
		CALL BLK
		MOV DX,0000H
		CALL CURSOR
		MOV DS:[SI],OFFSET LIN1
		CALL IMPRIMIR
		INC PAG
		CALL ACTIVA
		MOV DX,0000H
		CALL CURSOR
		CALL BLK
R1:		CALL TECLA
		CMP AL,"1"
		JNE R1
		MOV DS:[SI],OFFSET LIN2
		MOV DX,0C05H
		CALL CURSOR
		CALL IMPRIMIR
		MOV DS:[SI],OFFSET LIN3
		MOV DX 0E05H
		CALL CURSOR
		CALL IMPRIMIR
R3: 	MOV DS:[DX],OFFSET BUFFC
		CALL EDIT
		MOV DS:[DX],OFFSET BUFFN
		CALL EDIT
		MOV DS:[DI],OFFSET BUFFC
R2:		MOV AL,DS:[DI]
		CMP AL,"0"
		JB CORR
		CMP AL,"9"
		JA CORR
		INC DI
		DEC CANT
		CMP CANT,00H
		JNE R2
		JMP R4
CURSOR:	MOV AH,02H
		MOV BH,PAG
		INT 10H
		RETN
BLK:	MOV AH,09H
		MOV AL,20H
		MOV BH,PAG
		MOV CX,2000
		INT 10H
		RETN
IMPRIMIR:	MOV AH,09H
I1:		MOV AL,DS:[SI]
		CMP AL,"$"
		JE I2
		MOV BH,PAG
		MOV CX,0001H
		INT 10H
		INC SI
		JMP I1
I2:		RETN
ACTIVA:	MOV AH,05H
		MOV AL,PAG
		INT 10H
		RETN
TECLA:	MOV AH,01H
		INT 16H
		RETN
EDIT:	MOV AH,0AH
		INT 21H
		RETN
		END